## 3. [Data Model](https://docs.python.org/2/reference/datamodel.html)

### 3.1 Objects, values and types

- **_ Objects _**: Python’s abstraction for data.


    - All data is represented by objects or by relations between objects. 
    - Code is also represented by objects.
    
    
- Every object has an identity, a type and a value. 


    - An object’s identity never changes once created (think of it as the object’s address in memory). 
        - ‘is‘ operator compares the identity of two objects; 
        - id() function returns an integer representing its identity (currently implemented as its address). 
                
    - An object’s type is also unchangeable. 
        - determines the operations that the object supports (e.g., “does it have a length?”) and also 
        - defines the possible values for objects of that type. 
        - type() function returns an object’s type (which is an object itself). 
                
    - The value of some objects can change. 
        - Objects whose value can change are said to be mutable; 
        - objects whose value is unchangeable once they are created are called immutable. 
            - The value of an immutable container that contains a reference to a mutable object can change 
            - So, immutability is not strictly the same as having an unchangeable value, it is more subtle.
        - An object’s mutability is determined by its type; for instance, 
            - numbers, strings and tuples are immutable, while 
            - dictionaries and lists are mutable.
                    
- Objects are never explicitly destroyed; they may be garbage-collected when becoming unreachable. 


    - CPython currently uses a reference-counting scheme with (optional) delayed detection of cyclically linked garbage:
        - collects most objects as soon as they become unreachable, 
        - but is not guaranteed to collect garbage containing circular references.
    - Do not assume immediate deletion of objects when they become unreachable:
        - ex: always close files
        
- Note that the use of the tracing or debugging facilities may keep collectable objects alive.

- Also note that catching an exception with a ‘try...except‘ statement may keep objects alive.

In [38]:

# test some premitive or built-in types
# some of these are compiler implementation dependent

print '====>small integers are singletons'
a = 10
b = 10
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)

print '====>big integers are not singletons'
a = 2147483647
b = 2147483647
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)
print 

print '====>long integers are not singletons'
a = 3L
b = 3L
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)

a = 79228162514264337593543950336L
b = 79228162514264337593543950336L
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)
print

print '====>floats are not singletons'
a = 0.0
b = 0.0
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)
print

print '====>short strings are singletons'
a = 'abc'
b = 'abc'
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)

print '====>long strings are not singletons '
a = 'abc' * 100
b = 'abc' * 100
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)
print

print '====>empty tuples are same'
a = ()
b = ()
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)
print

print '====>non-empty tuples are different'
a = (1,)
b = (1,)
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)
print

print '====>empty sets are different'
a = set()
b = set()
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)
print

print '====>empty lists are different'
a = []
b = list()
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)
print

print '====>empty dictionaries are different'
a = dict()
b = {}
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)
print

print '====>below assign {} to a and b'
a = b = {}
print a is b
print a, id(a), type(a), '\n', b, id(b), type(b)
print


====>small integers are singletons
True
10 9266384 <type 'int'> 
10 9266384 <type 'int'>
====>big integers are not singletons
False
2147483647 54472984 <type 'int'> 
2147483647 54472720 <type 'int'>

====>long integers are not singletons
False
3 62574352 <type 'long'> 
3 62574256 <type 'long'>
False
79228162514264337593543950336 63447248 <type 'long'> 
79228162514264337593543950336 63447288 <type 'long'>

====>floats are not singletons
False
0.0 54484240 <type 'float'> 
0.0 54484072 <type 'float'>

====>short strings are singletons
True
abc 37763392 <type 'str'> 
abc 37763392 <type 'str'>
====>long strings are not singletons 
False
abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc 58825728 <type 'str'> 
abcabcabcabcabcabcabcabcabcabcabcabc

### 3.2. The standard type hierarchy

- Below is a list of the types that are built into Python. 
- Extension modules (written in C, Java, or other languages, depending on the implementation) can define additional types.
- Future versions of Python may add types to the type hierarchy (e.g., rational numbers, efficiently stored arrays of integers, etc.).

>Some of the type descriptions below contain a paragraph listing ‘special attributes.’ These are attributes that provide access to the implementation and are not intended for general use. Their definition may change in the future.

In [42]:
"""
None: This type has a single value.
"""
print '====>None'
print 'id:', id(None)
print 'type:', type(None)
print 'value:', None
print 'Is None True?', None is True
print 'Is None False', None is False
print 'truth value:', True if None else False

====>None
id: 506046248
type: <type 'NoneType'>
value: None
Is None True? False
Is None False False
truth value: False


In [43]:
"""
NotImplemented: This type has a single value.
    Numeric methods and rich comparison methods may return this value 
    if they do not implement the operation for the operands provided.    
"""
print '====>NotImplemented'
print 'id:', id(NotImplemented)
print 'type:', type(NotImplemented)
print 'value:', NotImplemented
print 'Is None True?', NotImplemented is True
print 'Is None False', NotImplemented is False
print 'truth value:', True if NotImplemented else False

====>None
id: 506046664
type: <type 'NotImplementedType'>
value: NotImplemented
Is None True? False
Is None False False
truth value: True


In [3]:
"""
Ellipsis: This type has a single value. 
    There is a single object with this value. 
    This object is accessed through the built-in name Ellipsis. 
    It is used to indicate the presence of the ... syntax in a slice. 
    Its truth value is true.
"""
print '====>Ellipsis'
print 'id:', id(Ellipsis)
print 'type:', type(Ellipsis)
print 'value:', Ellipsis
print 'Is None True?', Ellipsis is True
print 'Is None False', Ellipsis is False
print 'truth value:', True if Ellipsis else False
print '====>...'

class TestEllipsis(object):
    def __getitem__(self, item):
        if item is Ellipsis:
            return "Returning all items"
        else:
            return "return %r items" % item

x = TestEllipsis()
print x[2]
print x[...]

from numpy import arange
a = arange(16).reshape(2,2,2,2)
print a
print a[..., 0]
print a[..., 0].flatten()
print a[:,:,:,0]
print a[:,:,:,0].flatten()

====>Ellipsis
id: 506058424
type: <type 'ellipsis'>
value: Ellipsis
Is None True? False
Is None False False
truth value: True
====>...
return 2 items
Returning all items
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]
[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]
[ 0  2  4  6  8 10 12 14]
[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]
[ 0  2  4  6  8 10 12 14]


In [10]:
"""
numbers:
    A hierarchy of numeric abstract base classes.
    Implemented in the numbers module (PEP 3141) in CPython, where none of the types defined 
    in this module can be instantiated.

numbers.Number
    
    These are created by numeric literals and returned as results by arithmetic operators and arithmetic built-in functions. 
    
    Numeric objects are immutable; once created their value never changes. 
    
    Python numbers are of course strongly related to mathematical numbers, but subject to the limitations of numerical 
    representation in computers.
    
    The root of the numeric hierarchy. If you just want to check if an argument x is a number, 
    without caring what kind, use isinstance(x, Number)
"""

from numbers import Number
a = 1
b = 1.0
c = complex(11.0,4)
print a, '\t\t', type(a), '\t\t', isinstance(a, Number) 
print b, '\t\t', type(b), '\t\t', isinstance(b, Number) 
print c, '\t', type(c), '\t', isinstance(c, Number) 



1 		<type 'int'> 		True
1.0 		<type 'float'> 		True
(11+4j) 	<type 'complex'> 	True


In [28]:
"""
numbers.Integral

    These represent elements from the mathematical set of integers (positive and negative).

    There are three types of integers:

    Plain integers
        
        These represent numbers in the range -2147483648 through 2147483647. 
            (The range may be larger on machines with a larger natural word size, but not smaller.) 
        
        When the result of an operation would fall outside this range, the result is normally 
        returned as a long integer (in some cases, the exception OverflowError is raised instead). 
        
        For the purpose of shift and mask operations, integers are assumed to have a binary, 
        2’s complement notation using 32 or more bits, and hiding no bits from the user 
        (i.e., all 4294967296 different bit patterns correspond to different values).

    Long integers
        
        These represent numbers in an unlimited range, subject to available (virtual) memory only. 
        
        For the purpose of shift and mask operations, a binary representation is assumed, and 
        negative numbers are represented in a variant of 2’s complement which gives the illusion 
        of an infinite string of sign bits extending to the left.

    Booleans
        
        These represent the truth values False and True. 
        
        The two objects representing the values False and True are the only Boolean objects. 
        
        The Boolean type is a subtype of plain integers, and Boolean values behave like 
        the values 0 and 1, respectively, in almost all contexts, the exception being that 
        when converted to a string, the strings "False" or "True" are returned, respectively.

    The rules for integer representation are intended to give the most meaningful interpretation 
    of shift and mask operations involving negative integers and the least surprises 
    when switching between the plain and long integer domains. 
    
    Any operation, if it yields a result in the plain integer domain, 
    will yield the same result in the long integer domain or when using mixed operands. 
    The switch between domains is transparent to the programmer.

numbers.Real (float)

    These represent machine-level double precision floating point numbers. 
    
    You are at the mercy of the underlying machine architecture (and C or Java implementation) 
    for the accepted range and handling of overflow. 
    
    Python does not support single-precision floating point numbers; 
        the savings in processor and memory usage that are usually the reason for using these 
        are dwarfed by the overhead of using objects in Python, 
        so there is no reason to complicate the language with two kinds of floating point numbers.

numbers.Complex
    
    These represent complex numbers as a pair of machine-level double precision floating point numbers. 
    
    The same caveats apply as for floating point numbers. 
    
    The real and imaginary parts of a complex number z can be retrieved through the read-only attributes 
    z.real and z.imag.

CPython numbers module (https://docs.python.org/2/library/numbers.html):

    Defines a hierarchy of numeric abstract base classes
    
    numbers.Number
        ^
        |
    numbers.Complex
        ^
        |
    numbers.Real
        ^
        |
    numbers.Rational
        ^
        |
    numbers.Integral
    

"""

from numbers import Number, Integral, Real, Complex

print '====>the smallest and biggest integers'
a = -2147483648 
b =  2147483647
print a, id(a), type(a), isinstance(a, Number), isinstance(a, Integral), isinstance(a, Real), isinstance(a, Complex)
print b, id(b), type(b), isinstance(b, Number), isinstance(b, Integral), isinstance(b, Real), isinstance(b, Complex)
print

print '====>they become long integers when -1 or +1'
a  -= 1
b  += 1
print a, id(a), type(a), isinstance(a, Number), isinstance(a, Integral), isinstance(a, Real), isinstance(a, Complex)
print b, id(b), type(b), isinstance(b, Number), isinstance(b, Integral), isinstance(b, Real), isinstance(b, Complex)
print

print '====>boolean'
a  = True
b  = False
print a, id(a), type(a), isinstance(a, Number), isinstance(a, Integral), isinstance(a, Real), isinstance(a, Complex)
print b, id(b), type(b), isinstance(b, Number), isinstance(b, Integral), isinstance(b, Real), isinstance(b, Complex)
print 

print '====>integer operation'
print 1+1 == 1L + 1L
print 1+1 == 1L + 1
print

print '====>real'
a  = 1.0
b  = 2.0**500
print a, id(a), type(a), isinstance(a, Number), isinstance(a, Integral), isinstance(a, Real), isinstance(a, Complex)
print b, id(b), type(b), isinstance(b, Number), isinstance(b, Integral), isinstance(b, Real), isinstance(b, Complex)
print 

print '====>complex'
a  = complex(10,-20)
print a, id(a), type(a), str(a), a.real, a.imag, \
    isinstance(a, Number), isinstance(a, Integral), isinstance(a, Real), isinstance(a, Complex)
print 


====>the smallest and biggest integers
-2147483648 56931728 <type 'int'> True True True True
2147483647 56932184 <type 'int'> True True True True

====>they become long integers when -1 or +1
-2147483649 68480896 <type 'long'> True True True True
2147483648 68479096 <type 'long'> True True True True

====>boolean
True 505971488 <type 'bool'> True True True True
False 505971464 <type 'bool'> True True True True

====>integer operation
True
True

====>real
1.0 65153432 <type 'float'> True False True True
3.2733906079e+150 65153504 <type 'float'> True False True True

====>complex
(10-20j) 61344368 <type 'complex'> (10-20j) 10.0 -20.0 True False False True



In [29]:
"""
Sequences:

    Immutable sequences:
    
        Strings
        Unicode
        Tuples
        
    Mutable sequences:
    
        Lists
        Byte Arrays        
        The extension module array:
            provides an additional example of a mutable sequence type

"""

import sys
print sys.maxunicode

65535


In [30]:
"""
Set types:

    Sets
    Frozen sets
    
"""

a = set()
b = frozenset()
print a, id(a), type(a)
print b, id(b), type(b)

set([]) 58093640 <type 'set'>
frozenset([]) 10440264 <type 'frozenset'>


In [32]:
"""
Mappings:

    Dictionaries
    
"""
a = {}
print a, id(a), type(a)

{} 69804376 <type 'dict'>


In [37]:
"""
Callable types:

    User-defined functions
    User-defined methods

"""

def myFunction():
    pass
a = myFunction
print a, id(a), type(a)

class MyClass(object):
    
    def method1():
        pass
    
    def method2(self):
        pass
    
a = MyClass.method1
b = MyClass.method2
print a, id(a), type(a)
print b, id(b), type(b)
mc = MyClass()
a = mc.method1
b = mc.method2
print a, id(a), type(a)
print b, id(b), type(b)

<function myFunction at 0x0000000003766208> 58089992 <type 'function'>
<unbound method MyClass.method1> 60377200 <type 'instancemethod'>
<unbound method MyClass.method2> 60377272 <type 'instancemethod'>
<bound method MyClass.method1 of <__main__.MyClass object at 0x0000000004330AC8>> 61603632 <type 'instancemethod'>
<bound method MyClass.method2 of <__main__.MyClass object at 0x0000000004330AC8>> 60377200 <type 'instancemethod'>


In [3]:
"""
Callable types:

    Generator functions

"""

def myFunction():
    for i in range(10): 
        yield i

a = myFunction
print a, id(a), type(a)

for value in myFunction():
    print value,
print

it = myFunction()
while 1:
    try:
        value = it.next()
        print value,
    except StopIteration as e:
        print '\nSTOP'
        break

<function myFunction at 0x00000000038AB828> 59422760 <type 'function'>
0 1 2 3 4 5 6 7 8 9
0 1 2 3 4 5 6 7 8 9 
STOP


In [31]:
"""
Callable types:

    Built-in functions

"""

a = len
b = math.sin
print a, id(a), type(a)
print b, id(b), type(b)

dir(__builtins__)[:10]


<built-in function len> 10581960 <type 'builtin_function_or_method'>
<built-in function sin> 39483400 <type 'builtin_function_or_method'>


['ArithmeticError',
 'AssertionError',
 'AttributeError',
 'BaseException',
 'BufferError',
 'BytesWarning',
 'DeprecationWarning',
 'EOFError',
 'Ellipsis',
 'EnvironmentError']

In [32]:
"""
Callable types:

    Built-in methods

"""

b = []
a = b.append

print a, id(a), type(a)

dir(b)[:10]

<built-in method append of list object at 0x00000000038B6108> 66342600 <type 'builtin_function_or_method'>


['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__']

In [22]:
"""
Callable types:

    Class Types:
    
        Class types, or “new-style classes,” are callable. 
        
        These objects normally act as factories for new instances of themselves, 
        but variations are possible for class types that override __new__(). 
        
        The arguments of the call are passed to __new__() and, in the typical case, 
        to __init__() to initialize the new instance.
        
    Classic Classes
        
        When a class object is called, a new class instance is created and returned. 
        
        This implies a call to the class’s __init__() method if it has one. 
        
        Any arguments are passed on to the __init__() method. 
        
        If there is no __init__() method, the class must be called without arguments.

    Class instances
    
        Class instances are callable only when the class has a __call__() method; 
        x(arguments) is a shorthand for x.__call__(arguments).

"""

class class1(object):
    
    def __init__(self, a, b, c):
        print a, b, c
        
class1(1,2,3)

class class2(object):
    
    def __new__(self, a, b, c):
        print a, b, c
        
class2(1,2,3)

class class3(object):
    
    def __str__(self):
        return 'no constructor'
        
print class3()

class class4:
    
    def __init__(self, a, b, c):
        print a, b, c
        
class4(1,2,3)

class class5:
    
    def __str__(self):
        return 'no constructor'
        
print class5()

class class6:
    
    def __call__(self):
        print '__call__ get called'
    
class6()()

class class7(object):
    
    def __call__(self):
        print '__call__ get called'
    
class7()()

1 2 3
1 2 3
no constructor
1 2 3
no constructor
__call__ get called
__call__ get called


In [30]:
"""
Modules:

    Modules are imported by the import statement

"""

import numpy as np
print np.__name__
print np.__doc__[:10]
print np.__file__, '\n'
for a in np.__dict__.items()[:10]:
    print a

numpy

NumPy
===
C:\Anaconda2\envs\py2\lib\site-packages\numpy\__init__.pyc 

('disp', <function disp at 0x0000000003C064A8>)
('union1d', <function union1d at 0x0000000003C83828>)
('all', <function all at 0x0000000003A4F358>)
('issubsctype', <function issubsctype at 0x0000000003A14908>)
('savez', <function savez at 0x0000000003D299E8>)
('atleast_2d', <function atleast_2d at 0x0000000003A6EC18>)
('restoredot', <function restoredot at 0x0000000003A3ACF8>)
('ptp', <function ptp at 0x0000000003A4F4A8>)
('PackageLoader', <class 'numpy._import_tools.PackageLoader'>)
('ix_', <function ix_ at 0x0000000003C10908>)


In [46]:
"""
Classes:

    Both class types (new-style classes) and class objects (old-style/classic classes) 
    are typically created by class definitions. 
    
    A class has a namespace implemented by a dictionary object.

Class instances
    
    A class instance is created by calling a class object. 
    
    A class instance has a namespace implemented as a dictionary 
    which is the first place in which attribute references are searched.
    
    ...

"""

class c1(object):
    
    def test(self):
        pass
    pass

print c1, type(c1), c1.__dict__, c1.__module__, '\n'
a = c1()
print a, type(a), a.__dict__, '\n'
dir(c1)[-5:]

<class '__main__.c1'> <type 'type'> {'test': <function test at 0x0000000003F48198>, '__dict__': <attribute '__dict__' of 'c1' objects>, '__module__': '__main__', '__weakref__': <attribute '__weakref__' of 'c1' objects>, '__doc__': None} __main__ 

<__main__.c1 object at 0x0000000003F4C2B0> <class '__main__.c1'> {} 



['__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'test']

In [47]:
"""

Files:

Internal types:

    Code objects:
    
    Frame objects: execution frames
    
    Traceback objects: stack trace of an exception
    
    Slice objects: 
        
        Slice objects are used to represent slices when extended slice syntax is used. 
        e.g., a[i:j:step], a[i:j, k:l], or a[..., i:j].
        
        Support one method: 
            slice.indices(self, length)
    
    Static method objects:
    
    Class method objects
    
"""

print 'test later'

test later
